### ISSUE TITLE
Checks if we append to a skb

### ISSUE THREAD

**Issue by Stefan-Schmidt** [linux-wpan/linux-wpan#19]
So far we handle the cases where e pull out data of a skb but not when appending data to it.

**Comment by alexaring** [comment]
Hi,

I think this is not necessary. I imagine I was the initiator for this issue, but I think we don't need it.
What we need is to have the WORST-CASE headroom in part of compression.

See:
http://lxr.free-electrons.com/source/net/ieee802154/6lowpan/core.c#L160

Here we are sure that we have a headroom for the MAC header and worst-case decompression more bytes than before (6lowpan header can be larger than IPv6 header and NHC in worst case).

That's what "needed_headroom" is there for. We are save to pullout the data without checking.
NOTE: bluetooth 6lowpan doesn't have this and seems to be broken.

In case of decompression, we check always when pull out data if  we can. There could some perfomance step to check it once at start of decompression and if it's doesn't fit realloc headroom with skb_cow.

**Comment by Stefan-Schmidt** [comment]
Fair enough. Closing the issue.
